.\" Process this file with
.\" groff -man -Tutf8 pcmanx.1
.\"
.TH PCMANX 1 "2011-02-23" GNU "PCManX GTK+ User Manuals"
.SH NAME
pcmanx \- a bbs client
.SH DESCRIPTION
pcmanx is user-friendly telnet client mainly targets BBS users.

PCMan X is a newly developed GPL'd version of PCMan, a full-featured famous BBS client. It aimed to be an easy-to-use yet full-featured telnet client facilitating BBS browsing with the ability to process double-byte characters. Some handy functions like tabbed-browsing, auto-login and a built-in ANSI editor enabling colored text editing are also provided.
.PP
usage: pcmanx
.SH SEE ALSO
.IR http://code.google.com/p/pcmanx-gtk2/ ,
.IR http://groups.google.com/group/pcmanx
